# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-26 17:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moim', '0004_applier'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applier',
            old_name='meeting_id',
            new_name='meeting',
        ),
        migrations.AlterField(
            model_name='meeting',
            name='image_path',
            field=models.ImageField(upload_to='media/'),
        ),
    ]
